config/routes.rb
Zingly::Application.routes.draw do
  devise_for :users

  root 'static_pages#home'

  resources :groups, except: :index  do
    member do
      patch 'leave'
      patch 'remove_user'
    end
    resources :zings, except: :index do
      member do
        get 'list'
      end
    end
  end

  

end

app/models/zing.rb
# == Schema Information
#
# Table name: zings
#
#  id              :integer          not null, primary key
#  zing_for_id     :integer
#  zing_against_id :integer
#  description     :string(255)
#  creator_id      :integer
#  group_id        :integer
#  created_at      :datetime
#  updated_at      :datetime
#

class Zing < ActiveRecord::Base

  belongs_to :zing_for, class_name: 'User'
  belongs_to :zing_against, class_name: 'User'
  belongs_to :creator, class_name: 'User'

  validates :zing_for, presence: true
  validates :zing_against, presence: true
  validates :creator, presence: true
  #validates :description, presence: true

  validate :validate_zings

  private

    def validate_zings
      group = Group.find(self.group_id)
      if self.zing_for == self.zing_against
        errors.add(:base, 'users cannot zing themselves')
      end

      unless group.users.include?(self.zing_for)
        errors.add(:base, 'user must belong to group')
      end

      unless group.users.include?(self.zing_against)
        errors.add(:base, 'user must belong to group')
      end

      unless group.users.include?(self.creator)
        errors.add(:base, 'user must belong to group')
      end
    end
end

app/controllers/zings_controller.rb
class ZingsController < ApplicationController
  before_filter :authenticate_user!

  def new
    @zing = Zing.new
    @zing.group_id = params[:group_id]
    @zing.creator = current_user
    @group = Group.find(@zing.group_id)
  end

  def create
    @group = Group.find(params[:group_id])
    @zing = @group.zings.build(group_params)
    @zing.creator = current_user

    user_zing_id = params[:zing][:zing_for_id].to_i
    user_zinged_id = params[:zing][:zing_against_id].to_i

    user_zing_index = @group.rankings.index { |a| a.user_id == user_zing_id }
    user_zinged_index = @group.rankings.index { |a| a.user_id == user_zinged_id }

    user_zing = @group.rankings[user_zing_index]
    user_zinged = @group.rankings[user_zinged_index]

    user_zing.points += 1
    user_zing.zings_for += 1
    #user_zing.last_position = user_zing_index + 1

    user_zinged.points -= 1
    user_zinged.zings_against += 1
    #user_zinged.last_position = user_zinged_index + 1

    user_zing.save!
    user_zinged.save!

    set_last_position

    @group.save!

    if @zing.save!
      flash[:success] = 'Successfully added zing'
      redirect_to group_path(@group)
    else
      render 'new'
    end
  end

  def list
    @group = Group.find(params[:group_id])
    user_index = @group.users.index { |a| a.id == params[:id].to_i }
    user = @group.users[user_index]
    @zings = @group.zings.where('zing_for_id = ? OR zing_against_id = ?', user.id, user.id)
  end

  private
    def group_params
      params.require(:zing).permit(:zing_for_id, :zing_against_id, :creator, :description)
    end

    def set_last_position
      counter = 1
      @group.rankings.each do |user|
        user.last_position = counter
        counter += 1
      end
    end
end

app/helpers/zings_helper.rb
module ZingsHelper
end

app/views/zings/list.html.erb
<%= render 'groups/header' %>
<div class='row'>
	<section class='small-12 columns'>
		<table>
			<tr>
				<th>Zinger</th>
				<th>Zinged</th>
				<th>Description</th>
			</tr>
			<% @zings.each do |zing| %>
				<tr>
					<td><%= zing.zing_for.username %></td>
					<td><%= zing.zing_against.username %></td>
					<td><%= zing.description %>  </td>
				</tr>
			<% end %>
		</table>
	</section>
</div>

app/views/zings/new.html.erb
<% provide(:title, 'Add a Zing') %>
<h2>Add a zing for <%= @group.name %></h2>
<%= form_for(@zing, url: group_zings_path) do |f| %>

    <%= f.label :zing_for %>
    <%= collection_select(:zing, :zing_for_id, @group.users, :id, :username) %>

    <%= f.label :zing_against %>
    <%= collection_select(:zing, :zing_against_id, @group.users, :id, :username) %>

    <%= f.label :description %>
    <%= f.text_field :description %>

    <%= f.submit 'Create' %>
<% end %>