config/routes.rb
Zingly::Application.routes.draw do
  devise_for :users

  root 'static_pages#home'

  resources :groups, except: :index  do
    member do
      patch 'leave'
      patch 'remove_user'
    end
    resources :zings, except: :index do
      member do
        get 'list'
      end
    end
  end

  

end

app/models/group.rb
# == Schema Information
#
# Table name: groups
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  description :string(255)
#  admin_id    :integer
#  created_at  :datetime
#  updated_at  :datetime
#

class Group < ActiveRecord::Base
  belongs_to :admin, class_name: 'User'
  has_many :rankings, -> { order('points DESC, zings_for DESC, user_id ASC') }, autosave: true
  has_many :users, -> { order('rankings.points DESC, zings_for DESC') }, through: :rankings
  has_many :zings

  #before_validation :strip_whitespace

  validates :name, presence: true, length: { maximum: 50, minimum: 3 }

  validates :description, presence: true

  validates :admin, presence: true

  validates :users, presence: true

  private
    def strip_whitespace
      self.name = self.name.strip
      self.description = self.description.strip
    end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_filter :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_filter :admin_user, only: [:edit, :update, :destroy, :remove_user]
  before_filter :group_user, only: [:show, :leave]

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.admin = current_user
    @group.users << current_user
    if @group.save
      flash[:success] = 'New Group Created!'
      redirect_to root_url
    else
      render 'new'
    end
  end

  def join
    
  end

  def show
    @group = Group.find(params[:id])
  end

  def edit
    @group = Group.find(params[:id])
    @users = @group.users
  end

  def update
    if @group.update_attributes(group_params)
      flash[:success] = 'Group updated'
      redirect_to @group
    else
      render 'edit'
    end
  end

  def leave
    @group = Group.find(params[:id])
    if current_user == @group.admin
      flash[:non_form_error] = 'Unable to leave group while admin of the group'
      redirect_to @group
    else
      @group.users.delete(current_user)
      redirect_to @group
    end
  end

  def remove_user
    @group = Group.find(params[:id])
    user = @group.users.find(params[:user])

    if current_user == user
      flash[:non_form_error] = 'Cannot remove self while admin'
      redirect_to @group
    else
      @group.users.delete(user)
      flash[:success] = 'Removed user'
      redirect_to @group
    end
  end

  def destroy
    @group = Group.find(params[:id]).destroy
    redirect_to root_path
  end

  private
    def group_params
      params.require(:group).permit(:name, :description, :admin_id)
    end

    def admin_user
      @group = Group.find(params[:id])
      redirect_to group_path unless current_user == @group.admin
    end

    def group_user
      @group = Group.find(params[:id])
      redirect_to root_path unless @group.users.include?(current_user)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_header.html.erb
<div class="row">
  <header class="small-12 columns group-title">
    <h2><%= @group.name %></h2>
    <p><%= @group.description %></p>
    <p>Admin: <%= display_name(@group.admin) %></p>
    <% if @group.admin == current_user %>
      <%= link_to 'Edit Group', edit_group_path %>
      |
      <%= link_to 'Add Zing', new_group_zing_path(group_id: @group.id) %> |
    <% end %>
    <a href="#">Invite to Group</a> | 
    <%= link_to 'Leave group', leave_group_path, method: :patch %>
  </header>
</div>

app/views/groups/edit.html.erb
<% provide(:title, "Edit " + @group.name) %>
<% @group.users.each do |user| %>
    <li><%= user.email %></li>
  <% end %>
<h1> <%= @group.name %> </h1>
<%= form_for(@group) do |f| %>
  
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :description %>
  <%= f.text_area :description %>

  <hr />
  <p>change the admin of this group?</p>
  <%= collection_select(:group, :admin_id, @group.users, :id, :username) %>

  <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
<% end %>




<hr />
<p>Delete this group?</p>
<%= link_to "Delete Group", group_path, method: :delete %>

app/views/groups/new.html.erb
<% provide(:title, 'Create new group') %>
<%= form_for(@group, url:groups_path) do |f| %>

    <%= f.label :name %>
    <%= f.text_field :name, required: true %>

    <%= f.label :description %>
    <%= f.text_area :description, required: true %>

    <%= f.submit 'Create' %>
<% end %>

app/views/groups/show.html.erb
<% provide(:title, @group.name) %>
<%= render 'header' %>
<div class="row">
  <section class="small-12 columns user-list">
    <table>
      <tr>
        <th>Position</th>
        <th>Change</th>
        <th>User</th>
        <th>Zings</th>
        <th>Times Zinged</th>
        <th>Difference</th>
        <% if current_user == @group.admin %>
        <th>Admin</th>
        <% end %>
      </tr>
      <% counter = 1 %>
      <% @group.users.each do |user| %>
          <% index = counter - 1 %>
          <tr>
            <td><%= counter %></td>
            <%= render 'shared/position_change', group: @group, index: index, counter: counter %>
            <td><%= link_to user.username, list_group_zing_path(group_id: @group.id, id: user.id) %></td>
            <td><%= @group.rankings[index].zings_for %></td>
            <td><%= @group.rankings[index].zings_against %></td>
            <td><%= @group.rankings[index].points %></td>
            <% if current_user == @group.admin %>
                <td><%= link_to 'Remove user', remove_user_group_path(id: @group.id, user: user.id), method: :patch  %></td>
            <% end %>
          </tr>
          <% counter += 1 %>
      <% end %>
    </table>
  </section>
</div>