config/routes.rb
Zingly::Application.routes.draw do
  devise_for :users

  root 'static_pages#home'

  resources :groups, except: :index  do
    member do
      patch 'leave'
      patch 'remove_user'
    end
    resources :zings, except: :index do
      member do
        get 'list'
      end
    end
  end

  

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0)
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#  username               :string(255)
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  #before_validation :strip_username

  has_many :rankings
  has_many :groups, through: :rankings
  has_many :zings

  validate :user_not_blank

  #validates :username, allow_nil: true, length: { maximum: 30, minimum: 3 }

  def get_zing_count(group_id)
    @group = Group.find(group_id)
    zings = @group.zings.where(zing_for_id: self.id)
    zings.count
  end

  def get_zinged_count(group_id)
    @group ||= Group.find(group_id)
    zingeds = @group.zings.where(zing_against_id: self.id)
    zingeds.count
  end

  def get_zing_difference(group_id)
    get_zing_count(group_id) - get_zinged_count(group_id)
  end

  private



    def strip_username
      if self.username
        self.username = self.username.strip
      end
    end

    def user_not_blank
      strip_username

      if self.username
        # if username.blank? 
        #   errors.add(:base, 'username cannot be blank')
        # end
        if self.username.blank?
          self.username = nil

        elsif self.username.length < 3
          errors.add(:base, 'username is too short')

        elsif self.username.length > 30
          errors.add(:base, 'username is too long')
        end
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.email, class:"gravatar")
  end
end

app/views/users/_user_groups.html.erb
<div class="row">
  <section class="small-12 columns">
    <% if current_user.groups.any? %>
      <table>
        <tr>
          <th>Name</th>
          <th>Points</th>
          <th>Position</th>
          <th>Change</th>
        </tr>
        <% current_user.groups.each do |group| %>
        <tr>
          <td><%= link_to group.name, group_path(group.id) %></td>
          <% index = group.rankings.index { |user| user.user_id == current_user.id } %>
          <td><%= group.rankings[index].points %></td>
          <td><%= group.users.index { |a| a.id == current_user.id } + 1 %></td>
          <%= render 'shared/position_change', group: group, index: index, counter: index + 1 %>
        <% end %>
        </tr>
      </table>
    <% else %>
      <p>You do not belong to any groups, consider making one</p>
    <% end %>
  </section>
</div>

app/views/users/_user_header.html.erb
<div class="row">
  <section class="small-12 columns user-info">
    <header class="centered user-info-header" id="masthead">
      <%= link_to gravatar_for(current_user, size: 150), root_path, class: "small-3 columns", id: "first" %>
      <div id="second">
        <h2 class="user-title small-9 columns">
        <%= display_name(current_user) %>
        </h2>

        <%= link_to 'Edit Profile', edit_user_registration_path %>
        <%= link_to 'New Group', new_group_path %>
      </div>
      
    </header>
  </section>
</div>

app/views/users/_user_profile.html.erb
<% provide(:title, display_name(current_user)) %>
<%= render 'users/user_header' %>
<%= render 'users/user_groups' %>